<?xml version="1.0"?>
<robot name="three_wheel_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">
<!-- Uncomment this for debugging -->
<!-- <xacro:arg name="debug" default="true"/> -->

  <!-- Pi Constant -->
  <xacro:property name="pi_const" value="3.14159265"/>

  <!-- Dimensions -->
  <xacro:property name="a" value="1"/>     <!-- Length -->
  <xacro:property name="b" value="0.3"/>   <!-- Height -->
  <xacro:property name="c" value="0.6"/>   <!-- Width -->
  <xacro:property name="r" value="0.15"/>  <!-- Wheel radius -->
  <xacro:property name="d" value="0.1"/>   <!-- Wheel thickness -->

  <!-- Offsets -->
  <xacro:property name="s1" value="${b / 2 + r}"/>
  <xacro:property name="s2" value="${2 * r}"/>
  <xacro:property name="s3" value="${2 * r}"/>
  <xacro:property name="s4" value="${c / 2 + d / 2}"/>

  <!-- LiDAR Dimensions -->
  <xacro:property name="lidar_radius" value="0.1"/>
  <xacro:property name="lidar_height" value="0.06"/>
  <xacro:property name="lidar_offset_z" value="${s1 + b/2 + lidar_height/2}"/>

  <!-- Densities -->
  <xacro:property name="d1" value="2710.0"/>
  <xacro:property name="d2" value="2710.0"/>
  <xacro:property name="d3" value="2710.0"/>

  <!-- Masses -->
  <xacro:property name="m1" value="${d1 * a * b * c}"/>
  <xacro:property name="m2" value="${d2 * pi_const * r * r * d}"/>
  <xacro:property name="m3" value="${d3 * (4.0 / 3.0) * pi_const * r * r * r}"/>

  <!-- Inertias -->
  <xacro:property name="Ix_body" value="${(1.0/12.0) * m1 * (b*b + c*c)}"/>
  <xacro:property name="Iy_body" value="${(1.0/12.0) * m1 * (a*a + c*c)}"/>
  <xacro:property name="Iz_body" value="${(1.0/12.0) * m1 * (a*a + b*b)}"/>

  <xacro:property name="Iz_wheel" value="${0.5 * m2 * r * r}"/>
  <xacro:property name="I_wheel" value="${(1.0 / 12.0) * m2 * (3.0 * r * r + d * d)}"/>
  <xacro:property name="I_caster" value="${(2.0 / 5.0) * m3 * r * r}"/>

  <!-- Inertial Macros -->
  <xacro:macro name="inertia_body">
    <inertial>
      <origin xyz="0 0 ${s1}" rpy="0 0 0"/>
      <mass value="${m1}"/>
      <inertia ixx="${Ix_body}" ixy="0.0" ixz="0.0" iyy="${Iy_body}" iyz="0.0" izz="${Iz_body}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="inertia_wheel">
    <inertial>
      <origin xyz="0 0 0" rpy="1.570795 0 0"/>
      <mass value="${m2}"/>
      <inertia ixx="${I_wheel}" ixy="0.0" ixz="0.0" iyy="${I_wheel}" iyz="0.0" izz="${Iz_wheel}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="inertia_caster">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m3}"/>
      <inertia ixx="${I_caster}" ixy="0.0" ixz="0.0" iyy="${I_caster}" iyz="0.0" izz="${I_caster}"/>
    </inertial>
  </xacro:macro>

  <!-- Base and Body -->
  <link name="base_footprint"/>
  <joint name="body_link_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="body_link"/>
  </joint>

  <link name="body_link">
    <visual>
      <origin xyz="0 0 ${s1}" rpy="0 0 0"/>
      <geometry>
        <box size="${a} ${c} ${b}"/>
      </geometry>
      <material name="Grey">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${s1}" rpy="0 0 0"/>
      <geometry>
        <box size="${a} ${c} ${b}"/>
      </geometry>
    </collision>
    <xacro:inertia_body/>
  </link>

  <!-- Left Wheel -->
  <joint name="wheel1_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel1_link"/>
    <origin xyz="${-1 * s2} ${-1 * s4} ${r}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="50000" velocity="10"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>
  <link name="wheel1_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.570795 0 0"/>
      <geometry>
        <cylinder length="${d}" radius="${r}"/>
      </geometry>
      <material name="Yellow">
        <color rgba="1.0 1.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.570795 0 0"/>
      <geometry>
        <cylinder length="${d}" radius="${r}"/>
      </geometry>
    </collision>
    <xacro:inertia_wheel/>
  </link>

  <!-- Right Wheel -->
  <joint name="wheel2_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel2_link"/>
    <origin xyz="${-1 * s2} ${s4} ${r}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="50000" velocity="10"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>
  <link name="wheel2_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.570795 0 0"/>
      <geometry>
        <cylinder length="${d}" radius="${r}"/>
      </geometry>
      <material name="Yellow">
        <color rgba="1.0 1.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.570795 0 0"/>
      <geometry>
        <cylinder length="${d}" radius="${r}"/>
      </geometry>
    </collision>
    <xacro:inertia_wheel/>
  </link>

  <!-- Caster -->
  <joint name="caster_joint" type="fixed">
    <parent link="body_link"/>
    <child link="caster_link"/>
    <origin xyz="${s3} 0 ${r}" rpy="0 0 0"/>
  </joint>
  <link name="caster_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${r}"/>
      </geometry>
      <material name="Yellow">
        <color rgba="1.0 1.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${r}"/>
      </geometry>
    </collision>
    <xacro:inertia_caster/>
  </link>

  <!-- LiDAR -->
  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
      <material name="Blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <!-- LiDAR Joint (on top of body) -->
  <joint name="lidar_joint" type="fixed">
    <parent link="body_link"/>
    <child link="lidar_link"/>
    <origin xyz="0.3 0 ${lidar_offset_z}" rpy="0 0 0"/>
  </joint>

  <!-- Gazebo LiDAR Plugin -->
  <gazebo reference="lidar_link">
    <sensor name="lidar_sensor" type="ray">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>20</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.20</min>
          <max>15.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_laser_controller" filename="libgazebo_ros_laser.so">
        <topicName>/scan</topicName>
        <frameName>lidar_link</frameName>
      </plugin>
    </sensor>
  </gazebo>

  <!-- colors -->
  <gazebo reference="body_link">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="wheel1_link">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <gazebo reference="wheel2_link">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <gazebo reference="caster_link">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <gazebo reference="lidar_link">
    <material>Gazebo/Blue</material>
  </gazebo>


  <!-- Odom -->
  <gazebo>
    <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <namespace>/</namespace>
        <remapping>cmd_vel:=cmd_vel</remapping>
        <remapping>odom:=odom</remapping>
      </ros>
      <updateRate>50</updateRate>
      <leftJoint>wheel1_joint</leftJoint>
      <rightJoint>wheel2_joint</rightJoint>
      <wheelSeparation>0.6</wheelSeparation>
      <wheelDiameter>0.3</wheelDiameter>
      <torque>10</torque>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_footprint</robotBaseFrame>

      <publishTf>true</publishTf>  
    </plugin>
  </gazebo>

</robot>
